// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateCursor: typeof import('./src/components/AnimateCursor.vue')['default']
    Cog: typeof import('./src/components/cog.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MineBlock: typeof import('./src/components/MineBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusIndicator: typeof import('./src/components/statusIndicator.vue')['default']
    Vue3Guage: typeof import('./src/components/vue3Guage.vue')['default']
  }
}

export {}
