// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateCursor: typeof import('./src/components/AnimateCursor.vue')['default']
    Attr: typeof import('./src/components/Attr.vue')['default']
    BaseDataTable: typeof import('./src/components/BaseDataTable.vue')['default']
    CanvasExample: typeof import('./src/components/CanvasExample.vue')['default']
    Cog: typeof import('./src/components/cog.vue')['default']
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    CssFilter: typeof import('./src/components/CssFilter.vue')['default']
    Cube3D: typeof import('./src/components/Cube3D.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FunctionalComp: typeof import('./src/components/FunctionalComp.vue')['default']
    GlobalSearch: typeof import('./src/components/GlobalSearch.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Key: typeof import('./src/components/Key.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LostModal: typeof import('./src/components/LostModal.vue')['default']
    MineBlock: typeof import('./src/components/MineBlock.vue')['default']
    PostList: typeof import('./src/components/postList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusIndicator: typeof import('./src/components/statusIndicator.vue')['default']
    Vue3Guage: typeof import('./src/components/vue3Guage.vue')['default']
  }
}

export {}
