[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "17"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && pnpm config set strict-peer-dependencies false && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
