import type { Post } from '~/types'

export const notePostList = ref<Post[]>([
  {
    title: '打造你的专属最强IDE--Neovim',
    date: '2023-03-05',
    folder: 'note',
    fileName: 'neovim',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之联合类型的操作',
    date: '2022-12-12',
    folder: 'note',
    fileName: 'overviewTs12',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之字符串操作',
    date: '2022-12-08',
    folder: 'note',
    fileName: 'overviewTs11',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之元组类型的操作',
    date: '2022-12-01',
    folder: 'note',
    fileName: 'overviewTs10',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之对象类型的遍历',
    date: '2022-11-30',
    folder: 'note',
    fileName: 'overviewTs9',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之对象类型的操作',
    date: '2022-11-29',
    folder: 'note',
    fileName: 'overviewTs8',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之类型中的函数(泛型)',
    date: '2022-11-28',
    folder: 'note',
    fileName: 'overviewTs7',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之条件语句',
    date: '2022-11-27',
    folder: 'note',
    fileName: 'overviewTs6',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之获取类型所有属性key',
    date: '2022-11-26',
    folder: 'note',
    fileName: 'overviewTs5',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之通过变量取属性',
    date: '2022-11-26',
    folder: 'note',
    fileName: 'overviewTs4',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之类型的父子关系',
    date: '2022-11-26',
    folder: 'note',
    fileName: 'overviewTs3',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之类型数据和值',
    date: '2022-11-22',
    folder: 'note',
    fileName: 'overviewTs2',
    fileType: 'md',
  },
  {
    title: '纵览TypeScript之类型变量定义',
    date: '2022-11-20',
    folder: 'note',
    fileName: 'overviewTs1',
    fileType: 'md',
  },
  {
    title: '常用vim快捷操作',
    date: '2022-09-21',
    folder: 'note',
    fileName: 'vimOperator',
    fileType: 'md',
  },
  {
    title: 'TS中Type和Inrerface的区别',
    date: '2022-07-25',
    folder: 'note',
    fileName: 'typeVsInterface',
    fileType: 'md',
  },
])
